spring:
  application:
    name: super-ai-agents
  ai:
    dashscope:
      api-key: sk-b54295f09c8147308af17f975627f459
      chat:
        options:
          model: qwen-plus
      embedding:
        api-key: sk-b54295f09c8147308af17f975627f459
        options:
          model: text-embedding-v3
search-api:
  api-key: JKnHdC84NBZjqJpb9T3sj7kt