spring:
  application:
    name: super-ai-agents
  ai:
    openai:
      api-key: <your-minimax-api-key>
      base-url: https://api.minimaxi.com/v1
      chat:
        options:
          model: MiniMax-Text-01
      embedding:
        options:
          model: embo-01
search-api:
  api-key: JKnHdC84NBZjqJpb9T3sj7kt